const stocks = [
  { value: "AAPL", label: "Apple" },
  { value: "T", label: "AT&T" },
  { value: "GOOG", label: "Google LLC" },
  { value: "MO", label: "Altria Group" },
  { value: "AA", label: "Alcoa Corporation" },
  { value: "AXP", label: "American Express Company" },
  { value: "BABA", label: "Alibaba Group Holding Limited" },
  { value: "ABT", label: "Abbott Laboratories" },
  { value: "AMAT", label: "Applied Materials" },
  { value: "AMGN", label: "Amgen" },
  { value: "AIG", label: "American International Group" },
  { value: "ALL", label: "Allstate Corporation" },
  { value: "ADBE", label: "Adobe" },
  { value: "GOOGL", label: "Alphabet Inc." },
  { value: "ACN", label: "Accenture plc" },
  { value: "ABBV", label: "AbbVie Inc." },
  { value: "MT", label: "ArcelorMittal" },
  { value: "LLY", label: "Eli Lilly and Company" },
  { value: "APA", label: "APA Corporation" },
  { value: "ADP", label: "Automatic Data Processing" },
  { value: "AKAM", label: "Akamai Technologies" },
  { value: "NLY", label: "Annaly Capital Management" },
  { value: "ATVI", label: "Activision Blizzard" },
  { value: "ADSK", label: "Autodesk" },
  { value: "ADM", label: "Archer-Daniels-Midland Company" },
  { value: "WBA", label: "Walgreens Boots Alliance" },
  { value: "PANW", label: "Palo Alto Networks" },
  { value: "AMD", label: "Advanced Micro Devices" },
  { value: "AVGO", label: "Broadcom Inc." },
  { value: "EA", label: "Electronic Arts Inc." },
  { value: "AEM", label: "Agnico Eagle Mines Limited" },
  { value: "APD", label: "Air Products and Chemicals" },
  { value: "AMBA", label: "Ambarella" },
  { value: "NVS", label: "Novartis AG" },
  { value: "LULU", label: "Lululemon Athletica Inc." },
  { value: "BRK.AX", label: "Berkshire Hathaway Inc." },
  { value: "ARRY", label: "Array Technologies" },
  { value: "A", label: "Agilent Technologies" },
  { value: "ORLY", label: "O’Reilly Automotive" },
  { value: "AZO", label: "AutoZone" },
  { value: "AN", label: "AutoNation" },
  { value: "AZN", label: "AstraZeneca PLC" },
  { value: "BUD", label: "Anheuser-Busch InBev SA/NV" },
  { value: "BDX", label: "Becton, Dickinson and Company" },
  { value: "AB", label: "AllianceBernstein Holding L.P." },
  { value: "CS", label: "Credit Suisse Group AG" },
  { value: "AFL", label: "AFLAC Incorporated" },
  { value: "ADI", label: "Analog Devices" },
  { value: "ACIW", label: "ACI Worldwide" },
  { value: "AMP", label: "Ameriprise Financial" },
  { value: "AMZN", label: "Amazon.com" },
  { value: "MSFT", label: "Microsoft Corporation" },
  { value: "TSLA", label: "Tesla" },
  { value: "META", label: "Meta Platforms" },
  { value: "NFLX", label: "Netflix" },
];

export default stocks;
