// stocks.js
const stocks = [
  { value: "AAPL", label: "Apple" },
  { value: "MSFT", label: "Microsoft" },
  { value: "GOOGL", label: "Alphabet (Class A)" },
  { value: "GOOG", label: "Alphabet (Class C)" },
  { value: "AMZN", label: "Amazon" },
  { value: "NVDA", label: "NVIDIA" },
  { value: "META", label: "Meta Platforms" },
  { value: "BRK-A", label: "Berkshire Hathaway" },
  { value: "TSLA", label: "Tesla" },
  { value: "V", label: "Visa" },
  { value: "JPM", label: "JPMorgan Chase" },
  { value: "JNJ", label: "Johnson & Johnson" },
  { value: "UNH", label: "UnitedHealth Group" },
  { value: "PG", label: "Procter & Gamble" },
  { value: "XOM", label: "ExxonMobil" },
  { value: "HD", label: "Home Depot" },
  { value: "MA", label: "Mastercard" },
  { value: "LLY", label: "Eli Lilly" },
  { value: "MRK", label: "Merck & Co." },
  { value: "PEP", label: "PepsiCo" },
  { value: "COST", label: "Costco" },
  { value: "AVGO", label: "Broadcom" },
  { value: "PFE", label: "Pfizer" },
  { value: "KO", label: "Coca-Cola" },
  { value: "T", label: "AT&T" },
  { value: "CMCSA", label: "Comcast" },
  { value: "VZ", label: "Verizon" },
  { value: "INTC", label: "Intel" },
  { value: "CSCO", label: "Cisco" },
  { value: "ORCL", label: "Oracle" },
  { value: "CRM", label: "Salesforce" },
  { value: "ABT", label: "Abbott Labs" },
  { value: "NKE", label: "Nike" },
  { value: "DIS", label: "Disney" },
  { value: "WMT", label: "Walmart" },
  { value: "BAC", label: "Bank of America" },
  { value: "NFLX", label: "Netflix" },
  { value: "ADBE", label: "Adobe" },
  { value: "ACN", label: "Accenture" },
  { value: "TXN", label: "Texas Instruments" },
  { value: "QCOM", label: "Qualcomm" },
  { value: "UPS", label: "UPS" },
  { value: "MCD", label: "McDonald's" },
  { value: "UNP", label: "Union Pacific" },
  { value: "MDLZ", label: "Mondelez" },
  { value: "LOW", label: "Lowe's" },
  { value: "CB", label: "Chubb" },
  { value: "CVS", label: "CVS Health" },
  { value: "ADP", label: "ADP" },
  { value: "PYPL", label: "PayPal" },
  { value: "SBUX", label: "Starbucks" },
];

export default stocks;
